name: Terraform

on:
  workflow_dispatch:
    inputs:
      Action:
        type: choice
        description: Choose the Terraform Action
        options: 
        - PLAN
        - APPLY
        - DESTROY
      Resource:
        type: choice
        description: Choose the Resource
        options:
        - test
        - cloud_functions
        - storage_bucket

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./test
    steps:
        - name: Checkout
          if:  github.event.inputs.Action == 'PLAN'
          uses: actions/checkout@v3

        - name: Setup Terraform
          if:  github.event.inputs.Action == 'PLAN'
          uses: hashicorp/setup-terraform@v1
        
        - name: Terraform Plan
          if:  github.event.inputs.Action == 'PLAN'
          run: |
            echo "./${ { github.event.inputs.Resource } }"
            terraform init
            terraform plan
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_KEY }}


  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: "./${ { github.event.inputs.Resource } }"
    steps:
        - name: Checkout
          if:  github.event.inputs.Action == 'APPLY'
          uses: actions/checkout@v3
        
        - name: Setup Terraform
          if:  github.event.inputs.Action == 'APPLY'
          uses: hashicorp/setup-terraform@v1
        
        - name: Terraform Apply
          if:  github.event.inputs.Action == 'APPLY'
          run: |
            terraform init
            terraform apply --auto-approve
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_KEY }}
